### ISSUE TITLE
Add support for leisure=bathing_place

### ISSUE THREAD

**Issue by ToastHawaii** [ToastHawaii/priceless-map#12]

**Comment by Binnette** [comment]
TY @ToastHawaii for letting me discover this tag ❤ https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dbathing_place

**Comment by Binnette** [comment]
Do you know, there is also : https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dswimming_area
We need to check, but it seems to be "free".

**Comment by ToastHawaii** [comment]
@Binnette You are welcome. :)
Yes these are already displayed: https://priceless.zottelig.ch/?offers=sport%2Fbath&info=sport%2Fbath

Based on https://wiki.openstreetmap.org/wiki/Swimming_and_bathing I only show swimming areas that are not inside a bath. ;)

**Comment by ToastHawaii** [comment]
I just saw that I have already implemented this. :)
