### ISSUE TITLE
Category in Popup 

### ISSUE THREAD

**Issue by pqhf5kd** [ToastHawaii/priceless-map#2]
I believe it would be beneficial for the pop up to indicate why the POI was included in the selected category's results.
For example, if I select the Bicycle category, 6 results are returned for Kosice. All 6 results have the same icon and the popup for each doesn't specify why it was returned. The POI selected in my example is a gas station that is tagged with compress_air=yes. Going anti-clock wise, the other 5 POIs are:
- Another gas station with compressed air
- A bicycle repair station
- A BMX track
- A cycling training area (I believe, it's just tagged as sport=cycling and I need to do more research)
- amenity=charging_station with bicycle=yes, which I'm not sure is correct

<img width="956" alt="image" src="https://user-images.githubusercontent.com/20027419/74107294-96fefb00-4b6e-11ea-9993-c6c786be86e8.png">

**Comment by ToastHawaii** [comment]
Thanks for the input. The category is now visible in the popup.
