### ISSUE TITLE
fee!=*

### ISSUE THREAD

**Issue by pqhf5kd** [ToastHawaii/priceless-map#3]
I'm finding some POIs are returned even if they have no fee= tag.

For example:
WLAN:
https://www.openstreetmap.org/edit?node=300613989#map=20/48.72254/21.25644
https://www.openstreetmap.org/edit?node=667097079#map=20/48.73068/21.24346
Compressed air:
https://www.openstreetmap.org/edit?node=2991269240#map=20/48.66534/21.20805
https://www.openstreetmap.org/edit?node=1799566579#map=20/48.66941/21.27193

My understanding was that these should only appear if they have been tagged with internet_access:fee=no and compressed_air:fee=no respectively?

**Comment by ToastHawaii** [comment]
Thank you for your interest in this project.
I'll check the "fee" tag, if it exists. Per tag I have defined a default if there is none "fee" tag.

For internet_access and compressed_air if there is none "fee" tag I show the POI on the map.
